// SINGLE SOURCE OF TRUTH for all UI translations. Each key carries BOTH
// languages side by side, so you edit one place per string and a missing
// translation is impossible to overlook. English is the source/fallback;
// Traditional Chinese (繁體 / Hong Kong, 書面語) is the target.
//
// To edit a string: find its key below and change the value. To add one: add
// the key here (en + zh), then call t("your.key") in a component.
// `{name}`-style placeholders are interpolated by t(key, vars).
//
// SUBJECTS holds DSE subject display names (Chinese only – the English form IS
// the canonical key, shared with the data pipeline). `zh` = full name,
// `chip` = the ultra-compact form for the grade-summary pills.

export type Entry = { en: string; zh: string };

export const STRINGS = {

  // – Common / shared –
  "common.back": { en: "Back", zh: "返回" },
  "nav.homeAria": { en: "JUPASCal 2026 – home", zh: "JUPASCal 2026 – 主頁" },
  "nav.primaryAria": { en: "Primary", zh: "主要導覽" },
  "common.editProfile": { en: "Edit Profile", zh: "編輯個人檔案" },
  "common.about": { en: "About", zh: "關於" },
  "common.settings": { en: "Settings", zh: "設定" },
  "common.lq": { en: "LQ", zh: "LQ" },
  "common.median": { en: "Median", zh: "中位數" },
  "common.uq": { en: "UQ", zh: "UQ" },
  "common.mean": { en: "Mean", zh: "平均值" },
  "common.expected_score": { en: "Expected", zh: "預期分數" },
  "common.medAbbr": { en: "M", zh: "M" },
  "common.meanAbbr": { en: "Avg", zh: "平均" },
  "common.estAbbr": { en: "Est", zh: "預估" },
  "common.show": { en: "Show", zh: "顯示" },
  "common.hide": { en: "Hide", zh: "隱藏" },
  "lang.label": { en: "Language", zh: "語言" },
  "lang.switchTo": { en: "Switch language", zh: "切換語言" },
  "theme.toDark": { en: "Switch to dark mode", zh: "切換至深色模式" },
  "theme.toLight": { en: "Switch to light mode", zh: "切換至淺色模式" },
  "theme.dark": { en: "Dark mode", zh: "深色模式" },
  "theme.light": { en: "Light mode", zh: "淺色模式" },

  // – Stepper –
  "step.grades": { en: "Grades", zh: "輸入成績" },
  "step.programme": { en: "Programme", zh: "選擇課程" },
  "step.compare": { en: "Compare", zh: "比較分數" },
  "stepper.progress": { en: "Progress", zh: "進度" },

  // – Mobile welcome / landing –
  "welcome.eyebrow": { en: "Unofficial JUPAS admissions calculator", zh: "非官方 JUPAS 收生計分器" },
  "welcome.headline.pre": { en: "Compare your DSE score across ", zh: "一次比較各大院校" },
  "welcome.headline.accent": { en: "all programmes", zh: "所有課程" },
  "welcome.headline.post": { en: "", zh: "收生分數" },
  "welcome.sub": { en: "Your score estimated for each programme's own weighting and measured against recent admission scores across all 10 institutions.", zh: "按各課程計分比重計算你的分數，並與全港10所院校往年收生分數比較，以判斷排位風險" },
  "welcome.slide1.label": { en: "Your Band A", zh: "你的 Band A" },
  "welcome.slide1.note": { en: "Most offers are from Band A", zh: "大部分取錄均來自 Band A" },
  "welcome.slide1.prog1": { en: "Veterinary Medicine", zh: "獸醫學" },
  "welcome.slide1.prog2": { en: "Global Business", zh: "環球商業" },
  "welcome.slide1.prog3": { en: "Data Science", zh: "數據科學" },
  // Risk tags on the slide-1 mockup reuse the product's own risk.* strings
  // (risk.safe / risk.risky / risk.highRisk) so the landing always matches the app.
  "welcome.slide1.cap": { en: "Per-slot risk across your A1–A3", zh: "A1–A3 各志願風險一目了然" },
  "welcome.slide2.note": { en: "Above median", zh: "高於中位數" },
  "welcome.slide2.programme": { en: "Psychology", zh: "心理學" },
  "welcome.slide2.score": { en: "your calculated score", zh: "你的分數（含比重）" },
  "welcome.slide2.cap": { en: "Your score vs past LQ / median / UQ", zh: "你的分數對比往年 LQ／中位數／UQ" },
  "welcome.slide3.label": { en: "Every institution", zh: "全部院校" },
  "welcome.slide3.note": { en: "2025 data", zh: "2025 年數據" },
  "welcome.slide3.statPrefix": { en: "", zh: "自動計算共 " },
  "welcome.slide3.statSuffix": { en: " programmes scored from your grades", zh: " 個課程的收生分數" },
  "welcome.slide3.cap": { en: "Every JUPAS programme, in one place", zh: "集中查看所有JUPAS 課程" },
  "welcome.gotoSlide": { en: "Go to slide {n}", zh: "前往第 {n} 張" },
  "welcome.getStarted": { en: "Get started", zh: "開始使用" },
  "welcome.footnote.pre": { en: "Free · open-source · unofficial · reference only · ", zh: "免費 · 開放原始碼 · 非官方 · 僅供參考 · " },
  "welcome.footnote.how": { en: "How it works ↗︎", zh: "運作原理 ↗︎" },

  // – About page –
  "about.eyebrow": { en: "About", zh: "關於" },
  "about.title": { en: "JUPASCal", zh: "JUPASCal" },
  "about.lede": { en: "An unofficial JUPAS admissions score calculator for comparing programmes and historical score benchmarks across Hong Kong universities.", zh: "非官方 JUPAS 收生計分器，可比較香港各大學課程及其往年收生分數基準。" },
  "about.free": { en: "JUPASCal is completely free and open-source. No account is needed, and there is no paid version.", zh: "JUPASCal 完全免費開源，毋須開設帳戶，亦沒有收費版本。" },
  "about.facts.institutions": { en: "institutions", zh: "所院校" },
  "about.facts.programmes": { en: "programmes", zh: "個課程" },
  "about.facts.baselines": { en: "score baselines", zh: "收生分數基準" },
  "about.scores.h": { en: "How scores work", zh: "如何計算分數？" },
  "about.scores.p": { en: "JUPASCal applies the 2025 scoring logic where available so your calculated scores are directly comparable to each institution's 2025 admission-score references. Eligibility checks use 2026 entrance requirements published by each institution.", zh: "JUPASCal 會採用 2025 年計分邏輯，讓你的分數可直接對照各院校公佈的2025入學分數參考；入學資格審核則採用各院校公佈的 2026 年入學要求。" },
  "about.disclaimer.h": { en: "Disclaimer", zh: "免責聲明" },
  "about.disclaimer.p": {
    en: "This tool is for general private reference only. It is not an official, complete, or authoritative source, and does not constitute professional advice. While reasonable care has been taken to keep the information accurate and up to date, errors, omissions, or differences from the latest official position may still exist. Before making programme choices or JUPAS ranking decisions, always verify the final admission requirements with official university and JUPAS sources. Use of this tool is at your own risk.",
    zh: "本工具僅供一般私人參考，並非官方、完整或具權威性的資料來源，亦不構成專業意見。本人已盡力確保資料準確及更新，惟內容仍可能有錯漏，或與最新官方資料有所不同。作出課程選擇或 JUPAS 志願排序前，請務必向各大學及 JUPAS 官方資料核實最終入學要求。使用者須自行判斷並承擔使用風險。"
  },
  "about.privacy.h": { en: "Privacy", zh: "私隱" },
  "about.privacy.p": {
    en: "JUPASCal runs entirely in your browser. Your grades, profiles and selections are saved on your own device, not on any server, and there is no account or sign-in. The app only loads the public programme data. If you choose to share a plan, the details are encoded in the link itself rather than stored online. No user data is or will be collected.",
    zh: "JUPASCal 完全在你的瀏覽器內運行。你的成績、檔案及選擇只儲存於你的裝置，並不會存放於任何伺服器，亦無需任何帳戶。此網站只會載入公開的課程數據。若你選擇分享計劃，相關資料只會儲存於該分享連結中。此網站沒有亦不會收集任何用家數據。"
  },
  "about.source.h": {
    en: "Report an error or feedback",
    zh: "回報錯誤或意見"
  },
  "about.source.p.pre": {
    en: "Found a wrong score, requirement, or anything off? You can report it or send feedback through the Google Form. JUPASCal is also open source on GitHub, where you can file an issue or contribute directly.",
    zh: "發現分數、入學要求或其他地方出錯？你可透過 Google 表單回報或提供意見。JUPASCal 亦於 GitHub 開源，你可在該處提交 issue 或直接參與貢獻。"
  },
  "about.source.github": { en: "View on GitHub ↗︎", zh: "前往 GitHub ↗︎" },
  "about.source.form": { en: "Report via Google Form ↗︎", zh: "透過 Google 表單回報 ↗︎" },
  "about.more.h": { en: "Data sources", zh: "數據來源" },
  "about.more.p": { en: "Programme weightings, entry requirements and admission scores are compiled from each institution's own published admissions materials and the official JUPAS site, then cross-checked against them. The figures are reference estimates and may lag the latest official updates.", zh: "課程的科目比重、入學要求及收生分數，均整理自各院校官方公佈的收生資料及 JUPAS 官方網站，並經逐一核對。所有數字僅屬參考估算，未必反映最新的官方更新。" },
  "about.version": { en: "Version", zh: "版本" },
  "about.beta": { en: "Public Beta", zh: "公開測試版" },
  "about.cycle": { en: "{year} entry", zh: "{year} 年入學" },
  "about.build": { en: "build", zh: "Build" },

  // – Advisor empty state –
  "advisorEmpty.eyebrow": { en: "Risk Analysis", zh: "風險分析" },
  "advisorEmpty.title": { en: "Add programmes to assess your plan", zh: "加入課程後評估整體志願" },
  "advisorEmpty.lede": { en: "Once you add programmes, this panel weighs each choice against past admission data, highlights the main risks, and suggests safer alternatives in the same field.", zh: "加入課程後，本面板會對照歷年收生數據評估各個志願，指出主要風險，並建議方向相近而較穩妥的選擇。" },
  "advisorEmpty.checkHeading": { en: "What the analysis covers", zh: "分析涵蓋以下各項" },
  "advisorEmpty.check1": { en: "Whether your grades meet each programme's 2026 entry requirements.", zh: "按你的成績，檢查各志願是否符合 2026 年入學要求。" },
  "advisorEmpty.check2": { en: "Where each score sits against the 2025 LQ, median, and UQ.", zh: "各志願的計算分數相對 2025 年 LQ／中位數／UQ 的位置。" },
  "advisorEmpty.check3": { en: "Whether your Band A choices are realistic, and which ones are a reach.", zh: "Band A（A1–A3）的選擇是否穩妥，哪些則較為進取。" },
  "advisorEmpty.check4": { en: "Extra requirements like interviews, portfolios, or admission tests.", zh: "成績以外的要求，例如面試、作品集或入學試。" },
  "advisorEmpty.check5": { en: "Safer alternatives in a similar field for any risky Band A choice.", zh: "為較進取的 Band A 志願，建議方向相近而較穩妥的替代課程。" },
  "advisorEmpty.footnote": { en: "Scores are estimates based on 2025 admission data and 2026 weightings. Actual offers still depend on JUPAS ranking, places, interviews, and competition.", zh: "分數乃根據 2025 年收生數據及 2026 年計分比重估算；最終能否取錄，仍視乎 JUPAS 排位、學額、面試及競爭情況。" },

  // – Step 1: grade input –
  "grade.ariaPanel": { en: "DSE grades", zh: "DSE 成績" },
  "grade.eyebrow": { en: "Step 1", zh: "步驟一" },
  "grade.title": { en: "Input Your DSE Grades", zh: "輸入你的 DSE 成績" },
  "grade.edit": { en: "Edit", zh: "編輯" },
  "grade.done": { en: "Done", zh: "完成" },
  "grade.core": { en: "Core Subjects", zh: "核心科目" },
  "grade.mathExt": { en: "Mathematics Extended Part", zh: "數學延伸部分" },
  "grade.electives": { en: "Electives", zh: "選修科目" },
  "grade.elective": { en: "Elective {n}", zh: "選修科 {n}" },
  "grade.electiveAria": { en: "Elective {n} subject", zh: "第 {n} 個選修科目" },
  "grade.catCLang": { en: "Category C language", zh: "丙類語言科目" },
  "grade.reset": { en: "Reset grades", zh: "重設成績" },
  "grade.summaryAria": { en: "Entered grades summary", zh: "已輸入的成績概覽" },
  "grade.sum.chi": { en: "Chi", zh: "中文" },
  "grade.sum.eng": { en: "Eng", zh: "英文" },
  "grade.sum.math": { en: "Math", zh: "數學" },
  "grade.sum.csd": { en: "CSD", zh: "公社" },
  "grade.sum.m12": { en: "M1/2", zh: "M1/2" },
  "grade.sum.lang": { en: "Lang", zh: "語言" },

  // – Score scale / benchmark band labels –
  "band.aboveUq": { en: "Above UQ", zh: "高於 UQ" },
  "band.aboveMed": { en: "Above MED", zh: "高於中位" },
  "band.aboveLq": { en: "Above LQ", zh: "高於 LQ" },
  "band.belowLq": { en: "Below LQ", zh: "低於 LQ" },
  "band.noData": { en: "No data", zh: "暫無數據" },
  "bandLong.aboveUq": { en: "Above UQ", zh: "高於 UQ" },
  "bandLong.aboveMed": { en: "Above median", zh: "高於中位數" },
  "bandLong.aboveLq": { en: "Above LQ", zh: "高於 LQ" },
  "bandLong.belowLq": { en: "Below LQ", zh: "低於 LQ" },
  "bandLong.noScore": { en: "No score data", zh: "暫無分數數據" },
  "scale.no2025": { en: "No 2025 data", zh: "暫無 2025 年數據" },
  "scale.ariaNoData": { en: "Your score {score}, no 2025 admission data available", zh: "你的分數為 {score}，暫無 2025 年收生數據" },
  "scale.ariaFull": { en: "Your score {score} vs LQ {lq}, Median {median}, UQ {uq}, classified {band}", zh: "你的分數為 {score}，對比 LQ {lq}、中位數 {median}、UQ {uq}，評級為 {band}" },
  "scale.ariaBubble": { en: "Your score {score} – {band}", zh: "你的分數為 {score} – {band}" },

  // – Step 2: filters / programme select –
  "filters.eyebrow": { en: "Step 2", zh: "步驟二" },
  "filters.title": { en: "Select Programme(s)", zh: "選擇課程" },
  "filters.count": { en: "{shown} of {total} programmes shown", zh: "已顯示 {shown} / {total} 個課程" },
  "filters.aboutStep": { en: "About this step", zh: "關於此步驟" },
  "filters.howAria": { en: "How this step works", zh: "此步驟的運作方式" },
  "filters.selectingTitle": { en: "Selecting programmes", zh: "選擇課程" },
  "filters.selectingLede": { en: "Browse every JUPAS programme, pick the ones you're considering, then order them A1–B3.", zh: "瀏覽全部 JUPAS 課程，選取你正在考慮的課程，再排序為 A1–B3。" },
  "filters.tip.search.b": { en: "Search", zh: "搜尋" },
  "filters.tip.search.t": { en: " by full name, short form (BBA, law, CS), keyword, or JS code.", zh: "可用全名、簡稱（如 BBA、法律、CS）、關鍵字或 JS 編號。" },
  "filters.tip.filter.b": { en: "Filter", zh: "篩選" },
  "filters.tip.filter.t": { en: " by institution, eligibility, or score band.", zh: "可按院校、資格或分數區間篩選。" },
  "filters.tip.compact.b": { en: "Compact", zh: "精簡顯示" },
  "filters.tip.compact.t": { en: " the rows (toggle) to fit more programmes on screen.", zh: "課程列表（可切換），讓畫面容納更多課程。" },
  "filters.tip.delta.b": { en: "% (toggle)", zh: "％（可切換）" },
  "filters.tip.delta.t": { en: " shows the LQ / median / UQ gap as a percentage instead of points – and sorts by it.", zh: " 將 LQ／中位數／UQ 的差距以百分比（而非分數）顯示，並按此排序。" },
  "filters.tip.tap.b": { en: "Tap a programme", zh: "點選課程" },
  "filters.tip.tap.t": { en: " in the list to add it to your selection.", zh: "即可加入你的選擇。" },
  "filters.tip.drag.b": { en: "Drag a selected programme", zh: "拖動已選課程" },
  "filters.tip.drag.t": { en: " to reorder your priorities.", zh: "即可調整優先次序。" },
  "filters.tip.remove.b": { en: "Long-press", zh: "長按" },
  "filters.tip.remove.t": { en: " a Selected chip to remove it.", zh: "已選項目即可移除。" },
  "filters.programmeSearch": { en: "Programme search", zh: "課程搜尋" },
  "filters.searchPlaceholder": { en: "Try a name, short form or JS code – nursing · BBA · law · JS1001", zh: "輸入名稱、簡稱或 JS 編號 – 護理 · 工管 · 法律 · JS1001" },
  "filters.compact": { en: "Compact", zh: "列表顯示" },
  "filters.sort": { en: "Sort", zh: "排序" },
  "filters.filter": { en: "Filter", zh: "篩選" },
  // Benchmark difference display toggle (points vs % of the benchmark).
  "filters.deltaModeAria": { en: "Benchmark difference display", zh: "收生分差顯示方式" },
  "filters.deltaPts": { en: "Points", zh: "分數差" },
  "filters.deltaPct": { en: "% Diff", zh: "百分比" },
  "filters.deltaPtsTitle": { en: "Show the difference in raw points", zh: "以分數差距顯示" },
  "filters.deltaPctTitle": { en: "Show the difference as a percentage", zh: "以百分比差距顯示" },
  "filters.clearSearch": { en: "Clear search", zh: "清除搜尋" },
  "filters.showTools": { en: "Show sort & filter tools", zh: "顯示排序與篩選工具" },
  "filters.compactToComfort": { en: "Show comfortable programme cards", zh: "切換為卡片顯示" },
  "filters.compactToRows": { en: "Show compact programme rows", zh: "切換為列表顯示" },
  "filters.panelAria": { en: "Programme filters", zh: "課程篩選" },
  "filters.sortPanelAria": { en: "Programme sorting", zh: "課程排序" },
  "filters.sort.code": { en: "JS code", zh: "JS 編號" },
  "filters.sort.lqDiff": { en: "LQ diff", zh: "LQ差距" },
  "filters.sort.medianDiff": { en: "Med diff", zh: "中位數差距" },
  "filters.sort.uqDiff": { en: "UQ diff", zh: "UQ差距" },
  "filters.sort.quota": { en: "Quota", zh: "學額" },
  "filters.sort.benchmark": { en: "Best match", zh: "最佳配對" },
  "filters.institutionAria": { en: "Institution filter", zh: "院校篩選" },
  "filters.all": { en: "All", zh: "全部" },
  "filters.selectedOnly": { en: "Selected only", zh: "只顯示已選課程" },
  "filters.eligibleOnly": { en: "Eligible only", zh: "只顯示符合資格課程" },
  "filters.scoreRange": { en: "Score range", zh: "分數區間" },
  "filters.anyScoreRange": { en: "Any score range", zh: "不限分數" },
  "filters.interview": { en: "Interview", zh: "面試" },
  "filters.interviewAny": { en: "Any interview", zh: "不限面試" },
  "filters.interviewAfter": { en: "Post-results interview", zh: "放榜後面試" },
  "filters.interviewBefore": { en: "Pre-results interview", zh: "放榜前面試" },
  "results.interviewFlag.labelAfter": { en: "Post-results interview", zh: "放榜後面試" },
  "results.interviewFlag.titleAfter": { en: "Interview is listed after HKDSE result release", zh: "官方資料列明放榜後設面試" },
  "results.interviewFlag.labelBefore": { en: "Pre-results interview", zh: "放榜前面試" },
  "results.interviewFlag.titleBefore": { en: "Interview is listed before HKDSE result release", zh: "官方資料列明放榜前設面試" },
  "results.interviewFlag.labelBoth": { en: "Pre/post-results interview", zh: "放榜前後面試" },
  "results.interviewFlag.titleBoth": { en: "Interview is listed both before and after HKDSE result release", zh: "官方資料列明放榜前後均設面試" },

  // – Results list (table + cards) –
  "results.ariaPanel": { en: "Programme results", zh: "課程結果" },
  "results.col.programme": { en: "Programme", zh: "課程" },
  "results.col.institution": { en: "School", zh: "院校" },
  "results.col.status": { en: "Status", zh: "狀態" },
  "results.col.score": { en: "Score", zh: "分數" },
  "results.col.band": { en: "Band", zh: "Band" },
  // Table-only headers for the benchmark columns (cells show the raw score on
  // top + the diff below). Mobile chips keep the bare common.lq/median/uq.
  // The newline forces a clean two-line header (benchmark on top, 差距/Diff
  // below) via white-space:pre-line, so the columns can stay narrow.
  "results.col.lqDiff": { en: "LQ\nDiff", zh: "LQ\n差距" },
  "results.col.medianDiff": { en: "Median\nDiff", zh: "中位數\n差距" },
  "results.col.uqDiff": { en: "UQ\nDiff", zh: "UQ\n差距" },
  "results.yourScore": { en: "Your score", zh: "你的分數" },
  "results.eligible": { en: "Eligible", zh: "符合資格" },
  "results.checkReq": { en: "Not Eligible", zh: "未符合要求" },
  "results.removeFromCompare": { en: "Remove from comparison", zh: "從比較清單移除" },
  "results.addToCompare": { en: "Add to comparison", zh: "加入比較清單" },
  "results.quotaShort": { en: "Quota", zh: "學額" },
  "results.medShort": { en: "M", zh: "中" },

  // – Step 3: compare –
  "compare.eyebrow": { en: "Step 3", zh: "步驟三" },
  "compare.title": { en: "Compare Programmes", zh: "比較課程" },
  "compare.ariaPanel": { en: "Compare picked programmes", zh: "比較已選課程" },
  "compare.whatDoes": { en: "What does this do?", zh: "這一步有何作用？" },
  "compare.hintTitle": { en: "Comparing programmes", zh: "比較課程" },
  "compare.hintLede": { en: "See how each pick scores against past LQ / median / UQ admission bands.", zh: "查看每個志願的分數，並與歷年 LQ／中位數／UQ 收生區間比較。" },
  "compare.tip.tap.b": { en: "Tap a card", zh: "點選卡片" },
  "compare.tip.tap.t": { en: " to open full details – formula, requirements, and stats.", zh: "即可查看完整詳情：計分公式、入學要求及統計資料。" },
  "compare.tip.drag.b": { en: "Drag the slot handle", zh: "拖動志願手柄" },
  "compare.tip.drag.t": { en: " (A1, A2…) to reorder your priority.", zh: "（A1、A2…）即可調整志願優先次序。" },
  "compare.tip.number.b": { en: "Tap the slot number", zh: "點選志願編號" },
  "compare.tip.number.t": { en: " (A1, A2…) to swap a pick with any other slot.", zh: "（A1、A2…）即可與其他位置的志願對調。" },
  "compare.tip.swipe.b": { en: "Swipe or use the side arrows", zh: "滑動或使用兩側箭頭" },
  "compare.tip.swipe.t": { en: " inside a card to move between picks.", zh: "即可在不同志願之間切換。" },
  "compare.swapTo": { en: "Swap {code} to…", zh: "將 {code} 對調至…" },
  "compare.removePick": { en: "Remove {code}", zh: "移除 {code}" },
  "compare.addToSlot": { en: "Add a programme to slot {slot}", zh: "在 {slot} 加入課程" },
  "compare.addProgramme": { en: "Add a programme", zh: "加入課程" },
  "compare.removeSlot": { en: "Remove empty slot {slot}", zh: "移除空置的 {slot}" },
  "compare.filledAria": { en: "{slot} {code} {name}, tap for details", zh: "{slot} {code} {name}，點選查看詳情" },
  "compare.dragReorder": { en: "Drag {slot} to reorder", zh: "拖動 {slot} 以重新排序" },
  "compare.notEligible": { en: "Not eligible", zh: "不符合資格" },
  "compare.noMeetReq": { en: "Doesn't meet Entry Requirements!", zh: "未符合課程入學要求！" },
  "compare.places": { en: "Places", zh: "學額" },
  "compare.bandAApplicants": { en: "Band A applicants", zh: "Band A 申請人數" },
  "compare.applicantsPerPlace": { en: "Applicants / place", zh: "每個學額申請人數" },

  // – Preference planner (advisor / desktop) –
  "planner.ariaPanel": { en: "Programme choices planner", zh: "課程志願規劃" },
  "planner.eyebrow": { en: "Your plan", zh: "你的方案" },
  "planner.title": { en: "Programme choices", zh: "課程志願" },
  "planner.subtitleEmpty": { en: "Add programmes by code or name.", zh: "以課程編號或名稱加入。" },
  "planner.subtitleFilled": { en: "{filled} programme{extra} added", zh: "已加入 {filled} 個課程" },
  "planner.extraBelow": { en: " · +{n} below B3", zh: " · B3 以下另有 {n} 個志願" },
  "planner.slotsAria": { en: "Preference slots", zh: "志願位置" },
  "planner.col.code": { en: "Code", zh: "編號" },
  "planner.col.inst": { en: "Inst", zh: "院校" },
  "planner.col.programme": { en: "Programme", zh: "課程" },
  "planner.col.method": { en: "Method", zh: "計分方法" },
  "planner.col.score": { en: "Score", zh: "分數" },
  "planner.col.quota": { en: "Quota", zh: "學額" },
  "planner.col.elig": { en: "Elig", zh: "資格" },
  "planner.moveUp": { en: "Move {slot} up", zh: "將 {slot} 上移" },
  "planner.moveDown": { en: "Move {slot} down", zh: "將 {slot} 下移" },
  "planner.removeFrom": { en: "Remove {code} from {slot}", zh: "從 {slot} 移除 {code}" },
  "planner.removeEmpty": { en: "Remove empty {slot} slot", zh: "移除空置的 {slot}" },
  "planner.clearAll": { en: "Clear all", zh: "清除全部" },
  "planner.addSelection": { en: "+ Add new selection", zh: "+ 新增選擇" },
  "planner.focusDetail": { en: "Focus {code} in detail panel", zh: "在詳情面板查看 {code}" },
  "planner.meetsReq": { en: "Meets requirements", zh: "符合入學要求" },
  "planner.notMeetReq": { en: "Does not meet requirements", zh: "未符合入學要求" },
  "planner.emptySlot": { en: "Empty slot", zh: "空置志願" },
  "planner.noProgramme": { en: "No programme {code}", zh: "找不到課程 {code}" },
  "planner.alreadyAdded": { en: "{code} already added", zh: "{code} 已加入" },
  "planner.codeAria": { en: "JUPAS code", zh: "JUPAS 編號" },
  "planner.typeHint": { en: "Type a JUPAS code, or pick from the list below", zh: "輸入 JUPAS 編號，或從下方列表選取" },
  "planner.add": { en: "Add", zh: "加入" },

  // – Preference planner quick-add + Advisor Console (desktop / iPad) –
  "planner.quickAddHeading": { en: "Add a programme", zh: "加入課程" },
  "planner.browseToAdd": { en: "Add from Browse", zh: "前往瀏覽加入" },
  "planner.quickAddPlaceholder": { en: "Add by code or name…", zh: "輸入編號或名稱…" },
  "planner.quickAddAria": { en: "Add a programme by JUPAS code or name", zh: "以課程編號或名稱加入課程" },
  "planner.quickAddNoMatch": { en: "No matching programme", zh: "沒有相符的課程" },
  "planner.quickAddDone": { en: "Done", zh: "完成" },
  "planner.quickAddHint": { en: "Search by JUPAS code (e.g. JS4109) or programme name.", zh: "以 JUPAS 編號（如 JS4109）或課程名稱搜尋。" },
  "console.aria": { en: "Advisor console", zh: "升學輔導工作台" },
  "console.tabsAria": { en: "Console views", zh: "工作台檢視" },
  "console.tab.analyze": { en: "Analysis", zh: "分析" },
  "console.tab.browse": { en: "Browse", zh: "瀏覽課程" },
  "console.backToAnalysis": { en: "Back to analysis", zh: "返回分析" },

  // – Strategy summary (advisor) –
  "strategy.ariaPanel": { en: "Strategy summary", zh: "策略摘要" },
  "strategy.eyebrow": { en: "Advisor read", zh: "升學輔導分析" },
  "strategy.title": { en: "Strategy snapshot", zh: "策略概覽" },
  "strategy.eligibility": { en: "Eligibility", zh: "入學資格" },
  "strategy.eligibilityValue": { en: "{n}/{total} pass requirements", zh: "{n}/{total} 符合入學要求" },
  "strategy.aboveMedian": { en: "Above 2025 median", zh: "高於 2025 年中位數" },
  "strategy.aboveMedianValue": { en: "{n}/{total} choices", zh: "{n}/{total} 個志願" },
  "strategy.belowLq": { en: "Far below 2025 LQ", zh: "遠低於 2025 年 LQ" },
  "strategy.belowLqValue": { en: "{n} likely overshoot", zh: "{n} 個志願或過於進取" },
  "strategy.safety": { en: "B-band safety", zh: "B 組保底" },
  "strategy.safetyHas": { en: "Has a realistic safer choice", zh: "已有可行的保底選擇" },
  "strategy.safetyEmpty": { en: "B-band still empty", zh: "B 組仍未填寫" },
  "strategy.safetyNone": { en: "No realistic B-band safety", zh: "B 組缺乏可行保底" },
  "strategy.footnote": { en: "{n} picks use 2026 logic only – no 2025 benchmark available.", zh: "{n} 個志願只採用 2026 年計分邏輯，暫無 2025 年基準可供比較。" },

  // – Share button –
  "shareBtn.label": { en: "Share", zh: "分享" },
  "shareBtn.title": { en: "Open the share view", zh: "開啟分享畫面" },

  // – Profiles –
  "profile.renameProfile": { en: "Rename profile", zh: "重新命名個人檔案" },
  "profile.renameTitle": { en: "Rename Profile", zh: "重新命名個人檔案" },
  "profile.addTitle": { en: "New Profile", zh: "新增個人檔案" },
  "profile.namePlaceholder": { en: "Profile name", zh: "個人檔案名稱" },
  "profile.cancel": { en: "Cancel", zh: "取消" },
  "profile.save": { en: "Save", zh: "儲存" },
  "profile.select": { en: "Select profile", zh: "選擇個人檔案" },
  "profile.new": { en: "+ New", zh: "+ 新增" },
  "profile.createNew": { en: "Create new profile", zh: "建立新個人檔案" },
  "profile.moreOptions": { en: "More profile options", zh: "更多個人檔案選項" },
  "profile.rename": { en: "Rename", zh: "重新命名" },
  "profile.renameShort": { en: "Rename", zh: "重新命名" },
  "profile.delete": { en: "Delete", zh: "刪除" },
  "profile.startFresh": { en: "Start fresh (clear everything)", zh: "重新開始（清除全部）" },
  "profile.startFreshTitle": { en: "Wipe all locally-saved profiles, grades, and picks on this device", zh: "清除此裝置上所有本機儲存的個人檔案、成績及志願" },
  "profile.confirmDelete": { en: "Delete \"{name}\"?", zh: "確定刪除「{name}」？" },
  "profile.confirmReset": { en: "Start fresh? This deletes all your profiles, grades, and picks on this device. You can't undo this.", zh: "確定重新開始？此操作會清除此裝置上所有個人檔案、成績及志願，且無法復原。" },
  "profile.defaultName": { en: "My Profile", zh: "我的個人檔案" },
  "profile.scenarios": { en: "Scenarios", zh: "方案" },
  "profile.newScenario": { en: "+ New scenario", zh: "+ 新增方案" },
  "profile.renameCurrent": { en: "Rename current", zh: "重新命名目前方案" },
  "profile.deleteCurrent": { en: "Delete current", zh: "刪除目前方案" },
  "profile.switchProfile": { en: "Switch profile", zh: "切換個人檔案" },

  // – Detail panel –
  "detail.emptyEyebrow": { en: "Step 3", zh: "步驟三" },
  "detail.emptyTitle": { en: "Select a programme", zh: "選擇課程" },
  "detail.emptyLede": { en: "Choose one or more programmes to compare details, eligibility, score calculation, and the difference with 2025 admission scores.", zh: "選取一個或多個課程，即可比較課程詳情、入學資格、分數構成，以及與 2025 年入學分數的差距。" },
  "detail.selectedAria": { en: "Selected programmes", zh: "已選課程" },
  "detail.programmeList": { en: "Programme List ({n})", zh: "課程清單（{n}）" },
  "detail.suggestionList": { en: "Safer options ({n})", zh: "穩妥之選（{n}）" },
  "detail.emptySlot": { en: "Empty Slot", zh: "空置志願" },
  "detail.eligible": { en: "Eligible", zh: "符合資格" },
  "detail.suggested": { en: "Suggested", zh: "建議課程" },
  "detail.backupFor": { en: "Backup for {slot}", zh: "{slot} 的後備之選" },
  "detail.ineligible": { en: "Ineligible", zh: "不符合資格" },
  "detail.reqNotMet": { en: "Requirements not met", zh: "未符合入學要求" },
  "detail.prevProgramme": { en: "Previous programme", zh: "上一個課程" },
  "detail.nextProgramme": { en: "Next programme", zh: "下一個課程" },
  "detail.prev": { en: "Previous", zh: "上一個" },
  "detail.next": { en: "Next", zh: "下一個" },
  "detail.removeProgramme": { en: "Remove programme", zh: "移除課程" },
  "detail.newProgramme": { en: "2026 new programme", zh: "2026 年新課程" },
  "detail.quota": { en: "Quota: {n}", zh: "學額：{n}" },
  "detail.quotaShared": { en: "Quota: {n} (shared across {m} programmes)", zh: "學額：{n}（{m} 個課程共用）" },
  "detail.estimatedBenchmark": { en: "Estimated Score", zh: "估算分數" },
  "detail.hideBreakdown": { en: "Hide subject breakdown", zh: "隱藏科目細項" },
  "detail.showBreakdown": { en: "Show subject breakdown", zh: "顯示科目細項" },
  "detail.yourScore": { en: "Your score", zh: "你的分數" },
  "detail.calc2025": { en: "Calculated based on 2025 formula", zh: "按 2025 年公式計算" },
  "detail.noData2025": { en: "No 2025 admission data – comparing against 2026 logic only", zh: "暫無 2025 年收生數據 – 只與 2026 年計分邏輯比較" },
  "detail.tapBreakdownHide": { en: "Hide subject breakdown", zh: "隱藏科目細項" },
  "detail.tapBreakdownShow": { en: "Tap to see subject breakdown", zh: "點選查看科目細項" },
  "detail.noBenchmark": { en: "No 2025 LQ/Median/UQ score data is available for this programme.", zh: "此課程暫無 2025 年 LQ／中位數／UQ 分數數據。" },
  "detail.estimatedNotePre": { en: "These LQ and median figures are ", zh: "這些 LQ 及中位數是根據浸大公佈的成績分佈" },
  "detail.estimatedNoteBold": { en: "estimated", zh: "估算" },
  "detail.estimatedNotePost": { en: " from HKBU's published grade breakdowns (not actual admission scores), so treat them as approximate.", zh: "所得（並非實際收生分數），只可視作約數。" },
  "detail.lqCaveat": { en: "LQ above the median isn't a bug – this programme likely weighs more than your score (interview, portfolio, etc.).", zh: "LQ 高於中位數並非系統錯誤 – 此課程或會較重視分數以外的因素（如面試、作品集等）。" },
  "detail.formula2025Label": { en: "2025 comparison logic", zh: "2025 年比較邏輯" },
  "detail.formula2025Note": { en: "Used to compare your score against 2025 admission benchmarks.", zh: "用於將你的分數對照 2025 年收生基準。" },
  "detail.formula2026Label": { en: "2026 applicant reference", zh: "2026 年申請人參考" },
  "detail.formula2026Note": { en: "Current-year formula/weighting may differ; check this when making choices.", zh: "本年度計分公式／比重或有不同，排序時宜以此為準。" },
  "detail.formulaNA": { en: "Formula not available", zh: "暫無計算公式資料" },
  "detail.weightingDetails": { en: "Weighting details", zh: "比重詳情" },
  "detail.bestOf": { en: "Best {count}: {subjects}", zh: "最佳 {count} 科：{subjects}" },
  "detail.noWeighting": { en: "No specific subject weighting.", zh: "沒有特定科目比重。" },
  "detail.method2025": { en: "Method (2025)", zh: "計分方法（2025）" },
  "detail.bestSubjects": { en: "Best subjects", zh: "最佳科目" },
  "detail.counted": { en: "{used} of {total} counted", zh: "共 {total} 科，計入 {used} 科" },
  "detail.toggleFullName": { en: "Tap to show the full programme name", zh: "點按以顯示完整課程名稱" },
  "detail.tag.compulsory": { en: "Compulsory", zh: "必修" },
  "detail.tag.bonusPct": { en: "Bonus ({pct}%)", zh: "加分（{pct}%）" },
  "detail.tag.bonus": { en: "Bonus", zh: "加分" },
  "detail.tag.bestOfPool": { en: "Best-of pool", zh: "擇優科目" },
  "detail.tag.selected": { en: "Selected", zh: "已選用" },
  "detail.tag.notCounted": { en: "Not counted", zh: "未有計入" },
  "detail.grade": { en: "Grade", zh: "成績" },
  "detail.weight": { en: "Weight", zh: "比重" },
  "detail.score": { en: "Score", zh: "分數" },
  "detail.breakdownAria": { en: "Subject score breakdown", zh: "科目分數明細" },
  "detail.bandAOffers": { en: "Band A offers · {year}", zh: "Band A 取錄 · {year}" },
  "detail.rate": { en: "{rate}% rate", zh: "取錄率 {rate}%" },
  "detail.offersOfApps": { en: "{offers} of {apps} Band A applicants got offers", zh: "{apps} 名 Band A 申請人中，{offers} 人獲取錄" },
  "detail.compeRatio": { en: "≈ {ratio} Band A applicants competing for each offer", zh: "平均約 {ratio} 名 Band A 申請人競逐一個學額" },
  "detail.compeEven": { en: "Roughly one Band A applicant per offer – admissions reach Band B and below", zh: "約每個學額一名 Band A 申請人 – 取錄或延伸至 Band B 或以下" },
  "detail.compeFewer": { en: "Fewer Band A applicants than offers – admissions draw from lower bands", zh: "Band A 申請人少於學額 – 取錄或延伸至較低組別" },
  "detail.compeNone": { en: "No Band A offers in {year} – all offers went to lower bands", zh: "{year} 年並無 Band A 取錄 – 所有學額均給予較低組別申請人" },
  "detail.showHistory": { en: "Show {n}-year history", zh: "顯示 {n} 年數據" },
  "detail.hideHistory": { en: "Hide {n}-year history", zh: "隱藏 {n} 年數據" },
  "detail.offerHistoryAria": { en: "Band A offer history by year", zh: "按年份列出的 Band A 取錄紀錄" },
  "detail.col.year": { en: "Year", zh: "年份" },
  "detail.col.bandAApps": { en: "Band A apps", zh: "Band A 申請人" },
  "detail.col.offers": { en: "Offers", zh: "取錄人數" },
  "detail.col.rate": { en: "Rate", zh: "取錄率" },
  "detail.eligibility": { en: "Eligibility", zh: "入學資格" },
  "detail.passTally": { en: "{n}/{total} pass", zh: "{n}/{total} 符合" },
  "detail.unmetTally": { en: "{failed}/{total} unmet", zh: "{failed}/{total} 未符合" },
  "detail.showChecks": { en: "Show {n} requirement checks", zh: "顯示 {n} 項入學要求檢查" },
  "detail.hideChecks": { en: "Hide {n} requirement checks", zh: "隱藏 {n} 項入學要求檢查" },
  "detail.showUnmet": { en: "Show {n} unmet items", zh: "顯示 {n} 項未符合項目" },
  "detail.hideUnmet": { en: "Hide {n} unmet items", zh: "隱藏 {n} 項未符合項目" },
  "detail.checksAria": { en: "Admission requirement checks", zh: "入學要求檢查" },
  "detail.have": { en: "Have", zh: "已有" },
  "detail.need": { en: "Need", zh: "要求" },
  "detail.na": { en: "N/A", zh: "無" },
  "detail.showPassed": { en: "Show {n} passed requirements", zh: "顯示 {n} 項已符合的要求" },
  "detail.hidePassed": { en: "Hide {n} passed requirements", zh: "隱藏 {n} 項已符合的要求" },
  "detail.moreInfo": { en: "More information", zh: "更多資料" },
  "detail.sections": { en: "{n} sections", zh: "{n} 個部分" },
  "detail.showDetails": { en: "Show programme details", zh: "顯示課程詳情" },
  "detail.hideDetails": { en: "Hide programme details", zh: "隱藏課程詳情" },
  "detail.overview": { en: "Overview", zh: "概覽" },
  "detail.studyLevel": { en: "Study level", zh: "修讀程度" },
  "detail.tuition": { en: "First year tuition", zh: "首年學費" },
  "detail.moreInfoLink": { en: "More info ↗︎", zh: "更多資料 ↗︎" },
  "detail.contacts": { en: "Contacts", zh: "聯絡資料" },
  "detail.remarks": { en: "Remarks", zh: "備註" },
  "detail.officialPages": { en: "Official Pages", zh: "官方頁面" },
  "detail.officialJupas": { en: "Official JUPAS page", zh: "官方 JUPAS 頁面" },
  "detail.programmeWebsite": { en: "Programme website", zh: "課程網站" },
  "detail.notOnRecord": { en: "Not on record", zh: "沒有記錄" },
  "detail.noWebsiteRecord": { en: "No institution programme page on record", zh: "沒有院校課程頁面記錄" },
  "detail.reportError": { en: "Spotted a wrong score or weighting? Report here ↗︎", zh: "發現分數或科目比重有誤？按此回報 ↗︎" },
  "elig.chi": { en: "CHI", zh: "中文" },
  "elig.eng": { en: "ENG", zh: "英文" },
  "elig.math": { en: "MATH", zh: "數學" },
  "elig.csd": { en: "CSD", zh: "公民科" },
  "elig.elective1": { en: "Elective 1", zh: "選修一" },
  "elig.elective2": { en: "Elective 2", zh: "選修二" },
  "elig.none": { en: "None", zh: "無" },

  // – Share view –
  "share.panelAria": { en: "Shared JUPAS plan", zh: "已分享的 JUPAS 計劃" },
  "share.eyebrowReceived": { en: "Shared with you · 2026", zh: "對方分享的計劃 · 2026" },
  "share.eyebrowOwn": { en: "Your JUPAS plan · 2026", zh: "你的 JUPAS 計劃 · 2026" },
  "share.saveAsProfile": { en: "Save as my profile", zh: "儲存為我的個人檔案" },
  "share.openInCalc": { en: "Open in calculator", zh: "在計分器中開啟" },
  "share.viewAnalysis": { en: "View analysis", zh: "查看分析" },
  "share.viewModeBadge": { en: "Viewing a shared plan", zh: "正在檢視分享的計劃" },
  "share.recapAria": { en: "JUPAS recap card", zh: "JUPAS 總覽卡" },
  "share.recapFootnote": { en: "jupascal.com · unofficial JUPAS calculator · for reference only", zh: "jupascal.com · 非官方 JUPAS 計分器 · 僅供參考" },
  "share.showScoresToggle": { en: "Show my calculated scores on the card", zh: "在卡片上顯示我的計算分數" },
  "share.shareThisAria": { en: "Share this plan", zh: "分享此計劃" },
  "share.shareViaTitle": { en: "Share via…", zh: "分享…" },
  "share.copyLinkToShare": { en: "Copy link to share", zh: "複製分享連結" },
  "share.opening": { en: "Opening…", zh: "開啟中…" },
  "share.shared": { en: "Shared!", zh: "已分享！" },
  "share.whatsapp": { en: "WhatsApp", zh: "WhatsApp" },
  "share.shareWhatsapp": { en: "Share on WhatsApp", zh: "分享到 WhatsApp" },
  "share.threadsTitle": { en: "Threads (opens the Threads composer with the recap image)", zh: "Threads（開啟 Threads 撰文介面，並附上總覽圖）" },
  "share.shareThreads": { en: "Share on Threads", zh: "分享至 Threads" },
  "share.instagramTitle": { en: "Instagram (opens Instagram Stories on mobile, with the image ready to attach)", zh: "Instagram（在手機開啟 Instagram 限時動態，圖片已備妥可供附上）" },
  "share.shareInstagram": { en: "Share on Instagram", zh: "分享至 Instagram" },
  "share.dl.rendering": { en: "Rendering…", zh: "正在製作圖片…" },
  "share.dl.done": { en: "Saved!", zh: "已儲存！" },
  "share.dl.error": { en: "Failed – try again", zh: "失敗 – 請再試一次" },
  "share.dl.idle": { en: "Download image", zh: "下載圖片" },
  "share.copyLink": { en: "Copy link", zh: "複製連結" },
  "share.linkCopied": { en: "Link copied", zh: "已複製連結" },
  "share.linkCopiedBang": { en: "Link copied!", zh: "已複製連結！" },
  "share.advisorTitle": { en: "Share with a teacher or advisor", zh: "與老師或輔導員分享" },
  "share.advisorDesc": { en: "Sends a detailed analysis dashboard of your plan – best viewed on a tablet or computer.", zh: "傳送此計劃的詳細分析報告；建議使用平板或電腦查看。" },
  "share.advisorReady": { en: "Link ready!", zh: "連結已備妥！" },
  "share.advisorPreparing": { en: "Preparing…", zh: "準備中…" },
  "share.advisorBtn": { en: "Share analysis link", zh: "分享分析連結" },
  "share.disclaimer": { en: "Scores are estimated using 2025 admission data and 2026 weightings. Final admission depends on JUPAS ranking, places, interviews, and competition.", zh: "分數乃根據 2025 年收生數據及 2026 年計分比重估算。最終能否取錄，仍視乎 JUPAS 排位、學額、面試及整體競爭情況。" },
  "share.footerPrompt": { en: "Check your own JUPAS scores!", zh: "計算你自己的 JUPAS 分數" },
  "share.calcYourOwn": { en: "Calculate your own", zh: "計算我的分數" },
  "share.shareText": { en: "{name}'s JUPAS 2026 plan · {count} programmes", zh: "{name} 的 JUPAS 2026 計劃 · {count} 個課程" },
  "share.advisorShareTitle": { en: "{name} · JUPAS analysis", zh: "{name} · JUPAS 分析" },
  "share.advisorShareText": { en: "{name}'s JUPAS analysis – for your review", zh: "{name} 的 JUPAS 分析 – 供你參閱" },
  "share.toast.sheetOpened": { en: "Share sheet opened", zh: "已開啟分享面板" },
  "share.toast.imgCopied": { en: "Image copied – paste it into your chat or post", zh: "已複製圖片，可貼到對話或貼文中" },
  "share.toast.imgSaved": { en: "Image saved – share it from your downloads", zh: "圖片已儲存，可從下載項目分享" },
  "share.toast.linkCopiedShare": { en: "Link copied – paste anywhere to share", zh: "已複製連結，可貼到任何地方分享" },
  "share.toast.cantShareDownload": { en: "Couldn't share – try the Download button", zh: "無法分享 – 請改用下載按鈕" },
  "share.toast.cantShare": { en: "Couldn't share – try again", zh: "無法分享 – 請再試一次" },
  "share.toast.pickInstagram": { en: "Pick Instagram in the share sheet – scroll right if needed", zh: "請在分享面板中選擇 Instagram；如有需要，請向右滑動" },
  "share.toast.pickThreads": { en: "Pick Threads in the share sheet – scroll right if needed", zh: "請在分享面板中選擇 Threads；如有需要，請向右滑動" },
  "share.toast.pickWhatsapp": { en: "Pick WhatsApp in the share sheet – scroll right if needed", zh: "請在分享面板中選擇 WhatsApp；如有需要，請向右滑動" },
  "share.toast.openingInstagram": { en: "Opening Instagram – pick the recap image from your Photos.", zh: "正在開啟 Instagram – 請從相簿選取總覽圖片。" },
  "share.toast.igDesktopCopied": { en: "Image copied. Open Instagram on your phone to post it.", zh: "圖片已複製。請在手機開啟 Instagram 發佈。" },
  "share.toast.igDesktopSaved": { en: "Image saved. Open Instagram on your phone to post it.", zh: "圖片已儲存。請在手機開啟 Instagram 發佈。" },
  "share.toast.threadsPaste": { en: "Threads opened – long-press in the post to paste the image.", zh: "已開啟 Threads – 在貼文中長按即可貼上圖片。" },
  "share.toast.threadsAttach": { en: "Threads opened – attach the saved image to your post.", zh: "已開啟 Threads – 請將已儲存的圖片附加至貼文。" },
  "share.toast.waPaste": { en: "WhatsApp opened – long-press the message box to paste the image.", zh: "已開啟 WhatsApp – 長按訊息框即可貼上圖片。" },
  "share.toast.waAttach": { en: "WhatsApp opened – attach the saved image to your chat.", zh: "已開啟 WhatsApp – 請將已儲存的圖片附加至對話。" },
  "share.toast.linkCopiedClip": { en: "Link copied to clipboard", zh: "已複製連結至剪貼簿" },
  "share.toast.cantCopyAddr": { en: "Couldn't copy – copy it from the address bar instead", zh: "無法複製 – 請改從網址列複製" },
  "share.toast.advisorCopied": { en: "Advisor link copied – send it to your teacher", zh: "已複製分析連結 – 可傳送給老師" },
  "share.toast.cantCopy": { en: "Couldn't copy – try again", zh: "無法複製 – 請再試一次" },

  // – Analysis view (chrome) –
  "analysis.shareLabel": { en: "Share", zh: "分享" },
  "analysis.shareTitle": { en: "Open the shareable recap card for this plan.", zh: "開啟此計劃的可分享總覽卡。" },
  "analysis.panelAria": { en: "Portfolio analysis", zh: "志願組合分析" },
  "analysis.eyebrowShared": { en: "Shared plan · 2026", zh: "已分享計劃 · 2026" },
  "analysis.eyebrowOwn": { en: "Your chances · 2026", zh: "你的取錄機會 · 2026" },
  "analysis.stats": { en: "{total} picks · {eligible} eligible · {strong}/{bandA} realistic in Band A", zh: "{total} 個志願 · {eligible} 個符合資格 · Band A 有 {strong}/{bandA} 個較可行志願" },
  "analysis.noPicks": { en: "No programmes picked yet", zh: "尚未選擇任何課程" },
  "analysis.gradesHeading": { en: "DSE grades", zh: "DSE 成績" },
  "analysis.bandAEyebrow": { en: "Band A · A1–A3", zh: "Band A · A1–A3" },
  "analysis.bandANote": { en: "most offers come from A1-A3", zh: "大部分取錄來自 A1-A3" },
  "analysis.bandAEmpty": { en: "No Band A choices yet – A1-A3 are where your real chance is.", zh: "尚未有 Band A 志願 – A1-A3 是最關鍵的位置。" },
  "analysis.bandBEyebrow": { en: "Band B and below", zh: "Band B 及以下" },
  "analysis.bandBNote": { en: "offers rarely reach here", zh: "取錄較少延伸至此" },
  "analysis.showLower": { en: "Show Band B and below ({n})", zh: "顯示 Band B 及以下（{n}）" },
  "analysis.hideLower": { en: "Hide Band B and below ({n})", zh: "隱藏 Band B 及以下（{n}）" },
  "analysis.keyPoints": { en: "Key points", zh: "重點" },
  "analysis.notes": { en: "{n} notes", zh: "{n} 項提示" },
  "analysis.detailCta": { en: "See each programme in detail", zh: "查看每個課程的詳細資料" },
  "analysis.detailCtaSub": { en: "Full scores, requirements, and past results for every pick.", zh: "每個志願的完整分數、入學要求及歷年收生結果。" },
  "analysis.disclaimer": { en: "This is an automatic estimate based on 2025 admission scores and 2026 entrance requirements. For reference only – your real chances also depend on places, interviews, and how others apply.", zh: "此乃根據 2025 年收生分數及 2026 年入學要求自動估算，僅供參考，並非保證 – 實際取錄機會仍視乎學額、面試及其他申請人的情況。" },
  "analysis.wantOwn": { en: "Want to check your own chances?", zh: "想計算自己的取錄機會？" },
  "analysis.notesInterview": { en: "interview / portfolio", zh: "面試／作品集" },
  "analysis.notesFewPlaces": { en: "very few places ({n})", zh: "學額甚少（{n} 個）" },
  "analysis.openDetailAria": { en: "Open {code} {name} details", zh: "開啟 {code} {name} 詳情" },

  // – Alternative / safety suggestions (Advisor Console) –
  "suggest.heading": { en: "Safer options in the same direction", zh: "同方向的穩妥之選" },
  "suggest.note": { en: "{n} suggested", zh: "{n} 個建議" },
  "suggest.intro": { en: "These similar programmes look more within reach for this profile – consider them as backups.", zh: "以下同類課程以此成績較有把握，可考慮作後備之選。" },
  "suggest.forSlot": { en: "Backup for {slot} · {code}", zh: "{slot}（{code}）的後備之選" },
  "suggest.aboveUq": { en: "Above UQ", zh: "高於上四分位" },
  "suggest.aboveMed": { en: "Above median", zh: "高於中位數" },
  "suggest.scoreVsMed": { en: "Your {score} vs median {median}", zh: "你的 {score}（中位數 {median}）" },
  "suggest.you": { en: "You", zh: "你" },
  "suggest.median": { en: "Median", zh: "中位數" },
  "suggest.fewPlaces": { en: "very few places ({n})", zh: "學額甚少（{n} 個）" },
  "suggest.add": { en: "Add to plan", zh: "加入計劃" },
  "suggest.addAria": { en: "Add {code} {name} to your plan", zh: "將 {code} {name} 加入你的計劃" },
  "suggest.swap": { en: "Swap {slot}", zh: "替換 {slot}" },
  "suggest.swapAria": { en: "Replace {slot} with {code}", zh: "以 {code} 替換 {slot}" },
  "suggest.showMore": { en: "Show {n} more", zh: "顯示更多 {n} 個" },
  "suggest.showFewer": { en: "Show fewer", zh: "收起" },
  "suggest.none": { en: "No safer same-direction options were found for the picks that need a backup.", zh: "未能為需要後備的志願找到同方向而更穩妥的課程。" },

  // – Non-academic requirements (interview / portfolio / test) –
  "sel.type.interview": { en: "Interview", zh: "面試" },
  "sel.type.portfolio": { en: "Portfolio", zh: "作品集" },
  "sel.type.audition": { en: "Audition", zh: "試演／甄選" },
  "sel.type.physical": { en: "Physical test", zh: "體能測試" },
  "sel.type.practical": { en: "Practical test", zh: "術科測試" },
  "sel.type.written": { en: "Written test", zh: "筆試" },
  "sel.type.aptitude": { en: "Aptitude test", zh: "能力傾向測試" },
  "sel.type.oea": { en: "Other Experiences & Achievements (OEA)", zh: "其他經歷及成就 (OEA)" },
  "sel.oea.js2620": {
    en: "Document your sporting achievements in the JUPAS OEA. HKBU's non-JUPAS routes require certificates/testimonials of outstanding results in international or HK-representative competitions, so attaching equivalent proof (records, awards, a reference from your sports association/HKSI) strengthens your application.",
    zh: "在 JUPAS 的「其他經歷及成就」(OEA) 詳列你的體育成就。浸大的非聯招途徑要求提交國際賽事或代表香港比賽的傑出成績證明／推薦信，故聯招申請亦宜附上相關佐證（成績紀錄、獎項、體育總會或香港體育學院的推薦信）以增強競爭力。",
  },
  "sel.timing.pre": { en: "before HKDSE results", zh: "放榜前" },
  "sel.timing.post": { en: "after HKDSE results", zh: "放榜後" },
  "sel.timing.both": { en: "before & after HKDSE results", zh: "放榜前後" },
  "sel.salience.required": { en: "required", zh: "必須" },
  "sel.salience.weighty": { en: "counts toward selection", zh: "影響甄選" },
  "sel.salience.optional": { en: "may be invited", zh: "或獲邀參加" },
  "sel.tentative": { en: "maybe / when necessary", zh: "或需要／按需要" },
  "sel.inferred": { en: "likely (based on programme type)", zh: "（按課程類別推斷）" },
  "sel.stale": { en: "based on last year's info – not yet confirmed", zh: "（沿用去年資料，尚未確認）" },
  // Detail-page section
  "detail.selection.heading": { en: "Non-academic requirements", zh: "成績以外的要求" },
  "detail.selection.sub": { en: "What some programmes ask for in addition to your DSE score. Confirm details with the programme.", zh: "部分課程於 DSE 成績以外另設的要求；詳情請向課程查證。" },
  "detail.selection.source": { en: "Source text", zh: "來源文字" },
  "sel.structured.before": { en: "Pre-results", zh: "放榜前" },
  "sel.structured.after": { en: "Post-results", zh: "放榜後" },
  "sel.structured.date": { en: "Date / Timing", zh: "日期／時間" },
  "sel.structured.format": { en: "Format", zh: "形式" },
  // Analysis reminder finding (info, never a risk)
  "find.duties.interviewAfter": { en: "Interview (after results)", zh: "面試（放榜後）" },
  "find.duties.interviewBefore": { en: "Interview (before results)", zh: "面試（放榜前）" },
  "find.duties.interviewBoth": { en: "Interview (before & after results)", zh: "面試（放榜前後）" },
  "find.duties.title": { en: "Non-academic requirements", zh: "成績以外的要求" },
  "find.duties.detail": { en: "{groups}. These are considered apart of your score, so please prepare accordingly. Our data may be incomplete - confirm each with the programme.", zh: "{groups}。此為分數以外的要求，需額外準備；本工具的資料未必完整，請逐一向課程查證。" },

  
  // – Risk tags –
  "risk.safe": { en: "Safe", zh: "較有把握" },
  "risk.fair": { en: "Fair", zh: "機會尚可" },
  "risk.risky": { en: "Risky", zh: "較為進取" },
  "risk.highRisk": { en: "Highly risky", zh: "風險較高" },
  "risk.unsafe": { en: "Unsafe", zh: "危險" },
  "risk.blocked": { en: "Not eligible", zh: "未達入學要求" },
  "risk.unknown": { en: "No data", zh: "暫無數據" },
  "risk.lowerPossible": { en: "Possible", zh: "或有機會" },
  "risk.lowerUnlikely": { en: "Unlikely", zh: "機會較低" },

  // – App shell / orchestration –
  "app.loadError.title": { en: "Could not load JUPAS data", zh: "無法載入 JUPAS 數據" },
  "app.loadError.expected": { en: "Expected dataset:", zh: "預期數據：" },
  "app.sharedResults": { en: "Shared results", zh: "已分享的結果" },
  "app.loadingProfile": { en: "Loading profile...", zh: "正在載入個人檔案…" },
  "app.next.selectProgrammes": { en: "Select Programmes", zh: "選擇課程" },
  "app.next.review": { en: "Review {n} selected", zh: "檢視已選的 {n} 個課程" },
  "app.next.programmeDetail": { en: "Programme Detail", zh: "課程詳情" },
  "app.back.editGrades": { en: "Edit Grades", zh: "編輯成績" },
  "app.back.compare": { en: "Compare", zh: "比較" },
  "app.back.analysis": { en: "Analysis", zh: "分析" },
  "app.back.programme": { en: "Programme", zh: "課程" },
  "app.btn.analysePlan": { en: "Analyse plan", zh: "分析方案" },
  "app.btn.analysePlanTitle": { en: "Open a portfolio strategy read of your picks – eligibility, reach vs safety, and competition flags.", zh: "開啟你的排位組合策略分析，包括入學資格、風險，以及競爭提示。" },
  "app.btn.shareFriends": { en: "Share with friends", zh: "與朋友分享" },
  "app.btn.copyAdvisorLink": { en: "Copy analysis report link", zh: "複製分析報告連結" },
  "app.btn.copyAdvisorLinkTitle": { en: "Copy a link that opens this plan's analysis – send it to a teacher or advisor.", zh: "複製可開啟此方案分析的連結，傳送給老師或升學輔導員。" },
  "app.btn.shareFriendsTitle": { en: "Open the recap card view, optimized for screenshots / social posts.", zh: "開啟總覽卡，適合截圖或社交平台分享。" },
  "app.loading.text": { en: "Loading the latest programme data…", zh: "正在載入最新課程數據…" },
  "app.comparisonAria": { en: "Programme comparison", zh: "課程比較" },
  "app.drawer.eyebrow": { en: "Comparison drawer", zh: "比較區" },
  "app.drawer.title": { en: "Pick programmes to compare", zh: "選取課程以作比較" },
  "app.drawer.text": { en: "Use A1-A3 for dream, target, and safer choices. B1-B3 is useful for realistic backups and consultation.", zh: "A1–A3 應放入理想、目標及較穩妥的選擇；B1–B3 則適合作實際保底及諮詢之用。" },
  "app.preview.viewModePre": { en: "View mode – ", zh: "檢視模式 – " },
  "app.preview.saveBold": { en: "[Save as profile]", zh: "[儲存為個人檔案]" },
  "app.preview.toEdit": { en: " to start editing", zh: "即可開始編輯" },
  "app.preview.saveAsProfile": { en: "Save as profile", zh: "儲存為個人檔案" },
  "app.preview.discard": { en: "Discard", zh: "放棄" },
  "app.preview.hide": { en: "Hide", zh: "隱藏" },
  "app.preview.hideTitle": { en: "Minimise to a corner button – view-mode stays active", zh: "收納為角落按鈕 – 檢視模式會維持啟用" },
  "app.preview.fabAria": { en: "View mode – click to show options", zh: "檢視模式 – 點選顯示選項" },
  "app.preview.fabTitle": { en: "You're previewing a pasted URL – click to expand", zh: "你正在預覽貼上的網址 – 點選展開" },
  "app.preview.viewMode": { en: "View mode", zh: "檢視模式" },
  "app.btn.share": { en: "Share", zh: "分享" },
  "app.btn.shareTitle": { en: "Open the recap card view, optimized for screenshots or social posts.", zh: "開啟總覽卡，適合截圖或社交平台分享。" },
  "app.btn.analysis": { en: "Analysis", zh: "分析" },
  "app.btn.analysisTitle": { en: "See a detailed analysis of your picks – eligibility, reach vs safety, and competition flags.", zh: "查看各志願的詳細分析，包括資格、進取與保底，以及競爭提示。" },
  "app.removeAria": { en: "Remove {code}?", zh: "移除 {code}？" },
  "app.remove": { en: "Remove", zh: "移除" },
  "app.loadFailed": { en: "Failed to load data", zh: "載入數據失敗" },
  "app.desktopPlannerAria": { en: "Desktop JUPAS planner", zh: "桌面版 JUPAS 規劃工具" },
  "app.selectedOrderAria": { en: "Selected programme order", zh: "已選課程次序" },
  "app.footerReset": { en: "Reset", zh: "重設" },
  "app.selectedLabel": { en: "Selected", zh: "已選" },
  "app.none": { en: "None", zh: "無" },
  "app.moreCount": { en: "+{n} more", zh: "另有 {n} 個" },
  "app.reorganize": { en: "Reorganize", zh: "重新排列" },
  "app.reorganizeAll": { en: "Reorganize all picks", zh: "重新排列所有志願" },
  "app.reorganizeHint": { en: "Tap a slot number to swap a pick with another slot.", zh: "點選志願編號，即可與其他位置的志願對調。" },
  "app.expandPlanner": { en: "Expand to reorganize all picks", zh: "展開以重新排列所有志願" },
  "app.done": { en: "Done", zh: "完成" },
  "advisorEmpty.guidanceAria": { en: "Advisor guidance", zh: "升學輔導指引" },

  // – Analysis engine: findings & verdict (generated prose) –
  "find.elig.title.one": { en: "You're not eligible for {n} pick", zh: "你有 {n} 個志願未符合入學要求" },
  "find.elig.title.many": { en: "You're not eligible for {n} picks", zh: "你有 {n} 個志願未符合入學要求" },
  "find.elig.bandANote": {
    en: "Special consideration or alternative qualifications may still apply. ",
    zh: "個別課程或設彈性收生安排或接受其他資歷。"
  },
  "find.elig.detail.one": { en: "You don't meet the 2026 entry requirements for {slots}, so it can't give you an offer. {bandA}Tap it to see what's missing, then think about swapping it out.", zh: "你未符合 {slots} 的 2026 年入學要求，因此不會獲取錄。{bandA}開啟即可查看哪些要求尚未符合，並考慮將其替換。" },
  "find.elig.detail.many": { en: "You don't meet the 2026 entry requirements for {slots}, so they can't give you an offer. {bandA}Tap each one to see what's missing, and consider swapping them out.", zh: "你未符合 {slots} 的 2026 年入學要求，因此不會獲取錄。{bandA}逐一開啟即可查看哪些要求尚未符合，並考慮選擇其他課程。" },
  "find.eligOk.title.one": { en: "You're eligible for your pick", zh: "你符合所選志願的資格" },
  "find.eligOk.title.many": { en: "You're eligible for all {total} picks", zh: "你符合全部 {total} 個志願的資格" },
  "find.eligOk.detail": { en: "our grades have met the minimum admission requirements for all courses. Admission offers will depend on your scores, other considerations (such as interviews and OEA), and the level of competition among applicants.", zh: "你的成績已通過所有課程的最低入學要求；入學機會取決於你的分數、其他考慮（如面試、OEA）、及競爭人數。" },
  "find.bandAEmpty.title": { en: "Your Band A is empty", zh: "你的 Band A 尚未填寫" },
  "find.bandAEmpty.detail": { en: "The calculator relies heavily on your Band A choices to assess admission chances and recommend alternatives. Please place your top-choice programs in A1–A3 first, and then consider adding choices in the lower bands.", zh: "計分器主要根據你的 Band A 志願評估入學機會及建議其他選項。請先把主要志願放入 A1-A3，再考慮較低組別的志願。" },
  "find.bandAIncomplete.title": { en: "Use all three Band A slots", zh: "請善用全部三個 Band A 志願" },
  "find.bandAIncomplete.detail": { en: "The calculator relies heavily on your Band A choices to assess admission chances and recommend alternatives. Filling all three Band A slots helps provide a more complete and realistic analysis.", zh: "計分器主要根據你的 Band A 志願評估入學機會及建議其他選項。填滿三個 Band A 志願有助提供更完整及更貼近實際情況的分析。"},
  "find.bandAReview.detail.noRealistic": { en: "{review} need review. None of the current Band A choices is a realistic option based on the available score and eligibility data. {action}", zh: "{review} 需要檢查。根據現有分數及資格數據，目前 Band A 未有較可行選擇。{action}" },
  "find.bandAReview.detail.borderlineReview": { en: "{possible} is possible, but not a strong Band A option. Review {review}: {reasons}. {action}", zh: "{possible} 有機會，但未算穩妥的 Band A 選擇。請檢查 {review}：{reasons}。{action}" },
  "find.bandAReview.detail.borderlineOnly": { en: "{possible} is possible, but not a strong Band A option. {action}", zh: "{possible} 有機會，但未算穩妥的 Band A 選擇。{action}" },
  "find.bandAReview.detail.withReview": { en: "{realistic} is the realistic Band A option. Review {review}. {action}", zh: "只有{realistic} 是較為可行的 Band A 選擇。請檢查 {review}。{action}" },
  "find.bandAReview.detail.thin": { en: "{realistic} looks realistic, but Band A would be stronger with another realistic option. {action}", zh: "{realistic} 看來較可行，但 Band A 如有另一個可行選擇會較穩妥。{action}" },
  "find.bandAReview.action.blocked": { en: "Remove or replace {slots} first because the ineligibility wastes an offer.", zh: "先移除或替換 {slots}，避免因為未符合入學要求而浪費該志願。" },
  "find.bandAReview.action.borderline": { en: "Keep {slots} only as a possible choice, and add at least one stronger Band A option if available.", zh: "可保留 {slots} 作為有機會的選擇，但如有合適課程，應加入至少一個較穩妥的 Band A 志願。" },
  "find.bandAReview.action.none": { en: "Replace at least one Band A choice with a programme closer to your score range.", zh: "至少把一個 Band A 志願改為分數較接近你的課程。" },
  "find.bandAReview.action.moveEarlier.one": { en: "Consider moving {slots} up if you want to keep it, and use the later Band A slot for an safer option.", zh: "如保留 {slots} 作為進取選擇，可把它移到較前位置，並在較後的 Band A 選擇較低風險的課程。" },
  "find.bandAReview.action.moveEarlier.many": { en: "Consider moving {slots} up if you want to keep them, and use the later Band A slots for safer options.", zh: "如保留 {slots} 作為進取選擇，可把它們移到較前位置，並在較後的 Band A 選擇較低風險的課程。" },
  "find.bandAReview.action.review": { en: "Look for alternatives that are closer to your score range.", zh: "可尋找分數較接近你的其他課程。" },
  "find.bandAReview.action.fillMissing": { en: "Fill {slots} with realistic alternatives before relying on lower-band choices.", zh: "先以較可行的選擇填補 {slots}，再考慮較低組別志願。" },
  "find.bandAReview.action.addOption": { en: "Add another realistic Band A option if available.", zh: "如有合適課程，可加入另一個較可行的 Band A 選擇。" },
  "find.noAnchor.title": { en: "No realistic Band A option", zh: "Band A 暫無可行選擇" },
  "find.borderline.title": { en: "Band A has possible but not strong options", zh: "Band A 尚有機會，但未算穩妥" },
  "find.noAnchor.detail.one": { en: "{slots} is not currently a realistic Band A option. It is below the main admission score range, not eligible, or has no usable score data.", zh: "{slots} 目前並非可行的 Band A 選擇；它低於主要收生分數範圍、未符合資格，或缺乏可用分數數據。" },
  "find.noAnchor.detail.many": { en: "{slots} are not currently realistic Band A options. They are below the main admission score range, not eligible, or have no usable score data.", zh: "{slots} 目前並非可行的 Band A 選擇；它們低於主要收生分數範圍、未符合資格，或缺乏可用分數數據。" },
  "find.weak.reason.belowRange.one": { en: "It has a score below the main admission score range", zh: "分數低於主要收生分數範圍" },
  "find.weak.reason.belowRange.oneGrouped": { en: "{slots} is below the main admission score range", zh: "{slots} 低於主要收生分數範圍" },
  "find.weak.reason.belowRange.many": { en: "{slots} are below the main admission score range", zh: "{slots} 均低於主要收生分數範圍" },
  "find.weak.reason.aroundLq.one": { en: "{code} is around the LQ, but still weak for {slot}", zh: "約在 LQ 水平，但以 {slot} 而言仍然偏弱" },
  "find.weak.reason.aroundLq.oneGrouped": { en: "{slots} is around the LQ, but still weak for its Band A position", zh: "{slots} 約在 LQ 水平，但以其 Band A 位置而言仍然偏弱" },
  "find.weak.reason.aroundLq.many": { en: "{slots} are around the LQ, but are still weak for their Band A positions", zh: "{slots} 約在 LQ 水平，但以其 Band A 位置而言仍然偏弱" },
  "find.weak.reason.belowMedian.one": { en: "{code} is below the median, so it should be treated as higher risk in this position", zh: "低於中位數，因此在此位置應視為風險較高" },
  "find.weak.reason.belowMedian.oneGrouped": { en: "{slots} is below the median, so it should be treated as higher risk in this position", zh: "{slots} 低於中位數，因此在此位置應視為風險較高" },
  "find.weak.reason.belowMedian.many": { en: "{slots} are below the median, so they should be treated as higher risk in these positions", zh: "{slots} 低於中位數，因此在這些位置應視為風險較高" },
  "find.weak.reason.has": { en: "You have {bits}", zh: "{bits}" },
  "find.weak.bit.belowRange": { en: "a score below the main admission score range (< LQ)", zh: "你的分數低於主要收生分數範圍 (< LQ)" },
  "find.weak.bit.slotRisk": { en: "a risk level that is high for this slot", zh: "相對此位置風險較高" },
  "find.weak.bit.interview": { en: "an interview", zh: "需要面試" },
  "find.weak.bit.fewPlaces": { en: "very few places", zh: "學額甚少" },
  "find.weak.lead.one": { en: "{slots} is a realistic slot, but ", zh: "{slots} 是較可行的志願，但" },
  "find.weak.lead.many": { en: "{slots} are realistic slots, but ", zh: "{slots} 是較可行的志願，但" },
  "find.weak.title.one": { en: "{slots} is a risky pick", zh: "{slots} 屬偏進取志願" },
  "find.weak.title.many": { en: "Risky picks: {slots}", zh: "偏進取志願：{slots}" },
  "find.weak.detail.oneSolid": { en: "Review {review}: {reasons}. {action}", zh: "請檢查 {review}：{reasons}。{action}" },
  "find.weak.detail.manySolid": { en: "Review {review}: {reasons}. {action}", zh: "請檢查 {review}：{reasons}。{action}" },
  "find.aspirational.title": { en: "{slots} can stay as your dream choice", zh: "{slots} 可保留為你的夢想志願" },
  "find.aspirational.detail": { en: "{dream} is below the usual admission range, so on score alone it's a long shot. But {backups} are solid, and a JUPAS offer goes to the highest-ranked choice that accepts you – so an ambitious A1 doesn't reduce your chances at {backups}. If {dream} is genuinely your top choice, keeping it there is a reasonable risk to take.", zh: "{dream} 低於一般收生分數範圍，單以分數而言屬進取之選。不過 {backups} 較為穩妥；而在 JUPAS，你會獲排序最高且合資格的志願取錄，因此把進取志願放在 A1 並不會減低你在 {backups} 的機會。若 {dream} 確是你的首選，保留在此位置是值得一試的合理之選。" },
  "find.noData.title.one": { en: "{slots}: no 2025 data to estimate from", zh: "{slots}：暫無 2025 年數據可供估算" },
  "find.noData.title.many": { en: "No 2025 data to estimate: {slots}", zh: "暫無 2025 年數據可供估算：{slots}" },
  "find.noData.detail.one": { en: "{slots} has no 2025 admission scores on record – often a new or restructured programme – so its chance can't be estimated. It's fine to keep in Band A if you want it; just check its requirements and recent intake directly, since there's no benchmark to compare against.", zh: "{slots} 沒有 2025 年收生分數記錄（通常是新開辦或經調整的課程），因此無法估算其取錄機會。如你有意，仍可保留於 Band A；只是要自行查核其入學要求及近年收生情況，因為暫無基準可作比較。" },
  "find.noData.detail.many": { en: "{slots} have no 2025 admission scores on record – often new or restructured programmes – so their chances can't be estimated. They're fine to keep in Band A if you want them; just check their requirements and recent intake directly, since there's no benchmark to compare against.", zh: "{slots} 沒有 2025 年收生分數記錄（通常是新開辦或經調整的課程），因此無法估算其取錄機會。如你有意，仍可保留於 Band A；只是要自行查核它們的入學要求及近年收生情況，因為暫無基準可作比較。" },
  "find.bandAOk.title": { en: "A1-A3 has multiple realistic options", zh: "Band A 有多個較可行選擇" },
  "find.bandAOk.detail.one": { en: "{slots} scores at or above what most students got in with last year, but keep checking the other Band A slots too.", zh: "{slots} 的分數達到或高於去年大部分取錄學生的分數，但仍要一併檢查其他 Band A 志願。" },
  "find.bandAOk.detail.many": { en: "{slots} score at or above what most students got in with last year, so Band A includes more than one realistic option.", zh: "{slots} 的分數達到或高於去年大部分取錄學生的分數，因此 Band A 包含多於一個可行選擇。" },
  "find.bandAThin.title": { en: "Band A has limited realistic options", zh: "Band A 的可行選擇較少" },
  "find.bandAThin.detail": { en: "{slots} looks realistic, but Band A should ideally include more than one realistic option. Review the remaining Band A choices and adjust the order if needed.", zh: "{slots} 看來較可行，但 Band A 理想上應包含多於一個可行選擇。請檢查其餘 Band A 志願，並按需要調整次序。" },
  "find.fewPlaces.title.one": { en: "Very few places: {slots}", zh: "學額甚少：{slots}" },
  "find.fewPlaces.title.many": { en: "Very few places: {slots}", zh: "學額甚少：{slots}" },
  "find.fewPlaces.detail.one": { en: "{slots} takes very few students, so the score needed can jump around from year to year. Even with a good score, treat it as less safe than the numbers suggest.", zh: "{slots} 收生人數甚少，所需分數每年可能大幅波動。即使你分數達標，仍不應簡單視為低風險選擇。" },
  "find.fewPlaces.detail.many": { en: "{slots} take very few students, so the score needed can jump around from year to year. Even with a good score, treat them as less safe than the numbers suggest.", zh: "{slots} 收生人數甚少，所需分數每年可能大幅波動。即使你分數達標，仍不應簡單視為低風險選擇。" },
  "find.interviewStack.title": {
    en: "All Band A choices have required interviews or portfolios",
    zh: "所有 Band A 志願均要求面試或作品集"
  },
  "find.interviewStack.detail": {
    en: "{slots} explicitly require an interview or portfolio. Their risk cannot be assessed from scores alone, so review the non-academic requirements carefully.",
    zh: "{slots} 均明確要求面試或作品集。分數比較未必能完整反映取錄風險，應仔細考慮相關非學術要求。"
  },
  "find.lowerBuffer.title": { en: "Add a stronger lower-band backup", zh: "可加入較可行的低組別後備" },
  "find.lowerBuffer.detail.none": { en: "If Band A does not lead to an offer, lower-band choices only help when your score is clearly above the usual admitted range. Add one or two B/C choices where your score is above UQ or clearly above the median.", zh: "若 Band A 未能取錄，較低組別志願通常要分數明顯高於一般取錄水平才較有機會。可加入一至兩個分數高於 UQ 或明顯高於中位數的 B/C 志願。" },
  "find.lowerBuffer.detail.weak": { en: "{slots} are fine to include, but none is clearly above the usual admitted range. Consider using at least one lower-band slot for a programme where your score is above UQ or clearly above the median.", zh: "{slots} 可以保留，但當中暫未有志願明顯高於一般取錄水平。可考慮用至少一個較低組別位置，放入分數高於 UQ 或明顯高於中位數的課程。" },
  "find.scoreCaveat.title.one": { en: "{slots}: score data needs context", zh: "{slots}：分數數據需要一併解讀" },
  "find.scoreCaveat.title.many": { en: "Score data needs context: {slots}", zh: "分數數據需要一併解讀：{slots}" },
  "find.scoreCaveat.detail.one": { en: "An LQ above the median isn't a bug – this programme likely weighs more than your score (interview, portfolio, etc.).", zh: "LQ 高於中位數並非系統錯誤 – 此課程或會較重視分數以外的因素（如面試、作品集等）。" },
  "find.scoreCaveat.detail.many": { en: "An LQ above the median isn't a bug – these programmes likely weigh more than your score (interview, portfolio, etc.).", zh: "LQ 高於中位數並非系統錯誤 – 這些課程或會較重視分數以外的因素（如面試、作品集等）。" },
  "verdict.none.head": { en: "No programmes picked yet", zh: "尚未選擇任何課程" },
  "verdict.none.sub": { en: "Pick a few programmes to see your chances.", zh: "選擇數個課程後，即可查看你的取錄機會。" },
  "verdict.noBandA.head": { en: "Use your Band A choices", zh: "善用 Band A 志願" },
  "verdict.noBandA.sub": { en: "Most offers come from Band A – A1-A3 matters most.", zh: "大部分取錄來自 Band A，A1-A3 最為關鍵。" },
  "verdict.noSolid.head": { en: "No realistic A1-A3 option", zh: "A1-A3 暫無可行選擇" },
  "verdict.noSolid.sub": { en: "Your Band A picks sit below the main admission score range, so none should be treated as dependable.", zh: "你的 Band A 志願均低於主要收生分數範圍，因此現時沒有安全的選擇。" },
  "verdict.borderline.head": { en: "Band A lacks a strong option", zh: "Band A 缺少較安全的選擇" },
  "verdict.borderline.sub": { en: "{slots} may be possible, but it is not a strong Band A option.", zh: "{slots}的機會尚可，但未算穩妥的 Band A 選擇。" },
  "verdict.noOffer.head": { en: "No realistic Band A option", zh: "Band A 暫無可行選擇" },
  "verdict.noOffer.sub": { en: "No Band A pick is currently a realistic option.", zh: "目前沒有 Band A 志願是可行的選擇。" },
  "verdict.followup.head": { en: "Band A includes ineligible choice(s)", zh: "Band A 包含不符合資格的選擇" },
  "verdict.followup.sub": { en: "You don't meet the entry requirements for {blocked}, please review and consider swapping to other programmes.", zh: "你未符合 {blocked} 的入學要求，宜檢查並考慮選擇其他課程。" },
  "verdict.weak.head.one": { en: "Review {slots}", zh: "請檢查 {slots}" },
  "verdict.weak.head.many": { en: "Review {slots}", zh: "請檢查 {slots}" },
  "verdict.weak.solid.one": { en: "{slots} is realistic", zh: "{slots} 較有把握" },
  "verdict.weak.solid.many": { en: "{slots} are realistic", zh: "{slots} 較有把握" },
  "verdict.weak.risky.one": { en: "one is risky", zh: "其中一個志願偏進取" },
  "verdict.weak.risky.many": { en: "some are risky", zh: "部分志願偏進取" },
  "verdict.weak.sub.one": { en: "{problems} is riskier than {solid}.", zh: "{problems} 較 {solid} 進取。" },
  "verdict.weak.sub.many": { en: "{problems} are riskier than {solid}.", zh: "{problems} 較 {solid} 進取。" },
  "verdict.aspirational.head": { en: "Ambitious A1, solid backups", zh: "A1 進取，後備穩妥" },
  "verdict.aspirational.sub": { en: "{dream} is a reach on score, but {backups} keep your Band A realistic – keeping {dream} as your top choice is a sound plan.", zh: "{dream} 以分數計屬進取之選，但 {backups} 已令你的 Band A 仍有可行選擇 – 把 {dream} 保留為首選是穩健的安排。" },
  "verdict.noData.head": { en: "Band A can't be estimated yet", zh: "Band A 暫時無法估算" },
  "verdict.noData.sub": { en: "Your Band A picks have no 2025 data to compare against – they may be new programmes. Check their requirements and intake directly before relying on them.", zh: "你的 Band A 志願暫無 2025 年數據可供比較，它們可能是新開辦的課程。作準前請自行查核其入學要求及收生情況。" },
  "verdict.thin.head": { en: "Band A needs more realistic options", zh: "Band A 需要更多可行選擇" },
  "verdict.thin.sub": { en: "{slots} is realistic, but A1-A3 should include more than one realistic option.", zh: "{slots} 較可行，但 A1-A3 應包含多於一個可行選擇。" },
  "verdict.good.head": { en: "Your Band A is generally realistic", zh: "你的 Band A 整體較為可行" },
  "verdict.good.sub.one": { en: "{n} realistic option in your Band A.", zh: "你的 Band A 有 {n} 個較可行選擇。" },
  "verdict.good.sub.many": { en: "{n} realistic options in your Band A.", zh: "你的 Band A 有 {n} 個較可行選擇。" },

} satisfies Record<string, Entry>;

export const SUBJECTS = {
  "Chinese Language": { zh: "中國語文", chip: "中文"  },
  "English Language": { zh: "英國語文", chip: "英文"  },
  "Mathematics (Compulsory Part)": { zh: "數學（必修部分）", chip: "數學" },
  "Citizenship and Social Development": { zh: "公民與社會發展", chip: "公社" },
  "Mathematics Extended Part (Module 1 or 2)": { zh: "數學延伸部分（單元一或二）", chip: "M1/2" },
  "Mathematics Extended Part (Module 1)": { zh: "數學延伸部分（單元一）" , chip: "M1" },
  "Mathematics Extended Part (Module 2)": { zh: "數學延伸部分（單元二）" , chip: "M2" },
  "Biology": { zh: "生物", chip: "生物" },
  "Chemistry": { zh: "化學", chip: "化學" },
  "Physics": { zh: "物理", chip: "物理" },
  "Economics": { zh: "經濟", chip: "經濟" },
  "Geography": { zh: "地理", chip: "地理" },
  "History": { zh: "歷史", chip: "歷史" },
  "Chinese History": { zh: "中國歷史", chip: "中史" },
  "Information and Communication Technology": { zh: "資訊及通訊科技", chip: "ICT" },
  "Business, Accounting and Financial Studies": { zh: "企業、會計與財務概論", chip: "BAFS" },
  "Design and Applied Technology": { zh: "設計與應用科技", chip: "DAT" },
  "Health Management and Social Care": { zh: "健康管理與社會關懷", chip: "HSMC" },
  "Tourism and Hospitality Studies": { zh: "旅遊與款待", chip: "旅款" },
  "Chinese Literature": { zh: "中國文學", chip: "文學" },
  "Literature in English": { zh: "英語文學", chip: "英Lit" },
  "Technology and Living (Food Science and Technology)": { zh: "科技與生活（食品科學與科技）", chip: "科生" },
  "Visual Arts": { zh: "視覺藝術", chip: "視藝" },
  "Music": { zh: "音樂", chip: "音樂" },
  "Physical Education": { zh: "體育", chip: "體育" },
  "Ethics and Religious Studies": { zh: "倫理與宗教", chip: "倫宗" },
  "Integrated Science": { zh: "綜合科學", chip: "IS" },
  "Combined Science: Biology + Chemistry": { zh: "組合科學：生物 + 化學" },
  "Combined Science: Biology + Physics": { zh: "組合科學：生物 + 物理" },
  "Combined Science: Physics + Chemistry": { zh: "組合科學：物理 + 化學" },
  "French: Advanced Diploma of French Language Studies / Diploma of French Language Studies": { zh: "法文" },
  "German: Goethe-Certificate": { zh: "德文" },
  "Japanese: Japanese-Language Proficiency Test": { zh: "日文" },
  "Korean: Test of Proficiency in Korean II": { zh: "韓文" },
  "Spanish: Diploma of Spanish as a Foreign Language": { zh: "西班牙文" },
  "Urdu: Urdu (International)": { zh: "烏爾都文" },
} satisfies Record<string, { zh: string; chip?: string }>;
